### PR TITLE
Updated Readme: Instructions to connect Metamask to local hardhat node

### PR DESCRIPTION
**Pull request by raxhvl**
Hi Guys,

I think setting Metamask to connect to local hardhat node is a crucial step to be able to run the app locally.

### CODE REVIEW

**Comment by shubham-kanodia** [comment]
Can you also add procedure for setting up the account using private key?

**Comment by raxhvl** [comment]
Do you mean importing a hardhart account to metamask?

**Comment by shubham-kanodia** [comment]
When you run "npx hardhat node --network localhost", you get a few accounts with their private keys listed. We will need to add that account to metamask by importing that private key to access that account and its ethers

**Comment by raxhvl** [comment]
gotcha! can you check now?

**Pull request merged**
